### ISSUE TITLE
Prompt when no results are available

### ISSUE THREAD

**Issue by xuejianxianzun** [Decimation/SmartImage#14]
![snapshot](https://saber.love/f/2021-04-13_120410.png)
Thanks to this software, it is very convenient.
I have a question, is there no result available when the "similarity" is not green?
I can't be sure, so I have to wait every time. If it doesn't open the webpage, I can confirm that it has no results.
Is my guess correct? Or can you add a more direct prompt? Thank you!

**Comment by Decimation** [comment]
By default, result filtering is enabled which means that results below a certain similarity threshold aren't opened. For _SauceNao_, the threshold is `70%` (which is why the result in your screenshot wasn't opened).

>Or can you add a more direct prompt?

The `-` symbol in the result header indicates it was filtered (as seen in your screenshot)

>I have a question, is there no result available when the "similarity" is not green?

The similarity color is just a gradient (green indicating higher similarity, red indicating lower similarity).

You can disable this filtering feature in the main menu (option `5`).

**Comment by xuejianxianzun** [comment]
I see, thank you!
